apiVersion: v1
kind: Service
metadata:
  name: statistics-processing
  labels:
    app: statistics-processing
spec:
  ports:
    - name: grpc
      port: 50050
      targetPort: 50050
  selector:
    app: statistics-processing
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-processing
  labels:
    app: statistics-processing
spec:
  selector:
    matchLabels:
      app: statistics-processing
  replicas: 2
  template:
    metadata:
      labels:
        app: statistics-processing
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: statistics-processing
          image: gcr.io/visma-hiring/statistics-processing
          imagePullPolicy: Always
          command: ["/app/service"]
          args: []
          ports:
            - containerPort: 50050
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 768Mi
              cpu: 2500m
