[statistics]
max_unique_perc = 0.6 # Maximum percentage of unique values alloweed in a column over the document. 
key_column = "CompanyId" # Column used as key in agregation
summary_header = ",CompanyId,ColumnName,ColumnValue,Count\n" # Header of the report returned
delimiter = ',' # Delimiter to split the document rows
columns_exclude = []
max_number_of_cols = 25 # Determine the maximum number of columns to agreggate by (not available in the API)