# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/statistics_processing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/statistics_processing.proto',
  package='statisticsprocessing',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!proto/statistics_processing.proto\x12\x14statisticsprocessing\")\n\x16ProcessDocumentRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\'\n\x14ProcessDocumentReply\x12\x0f\n\x07summary\x18\x01 \x01(\x0c\x32\x84\x01\n\x13StatisticsProcesser\x12m\n\x0fProcessDocument\x12,.statisticsprocessing.ProcessDocumentRequest\x1a*.statisticsprocessing.ProcessDocumentReply\"\x00\x62\x06proto3'
)




_PROCESSDOCUMENTREQUEST = _descriptor.Descriptor(
  name='ProcessDocumentRequest',
  full_name='statisticsprocessing.ProcessDocumentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='statisticsprocessing.ProcessDocumentRequest.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=100,
)


_PROCESSDOCUMENTREPLY = _descriptor.Descriptor(
  name='ProcessDocumentReply',
  full_name='statisticsprocessing.ProcessDocumentReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='summary', full_name='statisticsprocessing.ProcessDocumentReply.summary', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['ProcessDocumentRequest'] = _PROCESSDOCUMENTREQUEST
DESCRIPTOR.message_types_by_name['ProcessDocumentReply'] = _PROCESSDOCUMENTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProcessDocumentRequest = _reflection.GeneratedProtocolMessageType('ProcessDocumentRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSDOCUMENTREQUEST,
  '__module__' : 'proto.statistics_processing_pb2'
  # @@protoc_insertion_point(class_scope:statisticsprocessing.ProcessDocumentRequest)
  })
_sym_db.RegisterMessage(ProcessDocumentRequest)

ProcessDocumentReply = _reflection.GeneratedProtocolMessageType('ProcessDocumentReply', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSDOCUMENTREPLY,
  '__module__' : 'proto.statistics_processing_pb2'
  # @@protoc_insertion_point(class_scope:statisticsprocessing.ProcessDocumentReply)
  })
_sym_db.RegisterMessage(ProcessDocumentReply)



_STATISTICSPROCESSER = _descriptor.ServiceDescriptor(
  name='StatisticsProcesser',
  full_name='statisticsprocessing.StatisticsProcesser',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=144,
  serialized_end=276,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProcessDocument',
    full_name='statisticsprocessing.StatisticsProcesser.ProcessDocument',
    index=0,
    containing_service=None,
    input_type=_PROCESSDOCUMENTREQUEST,
    output_type=_PROCESSDOCUMENTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATISTICSPROCESSER)

DESCRIPTOR.services_by_name['StatisticsProcesser'] = _STATISTICSPROCESSER

# @@protoc_insertion_point(module_scope)
